### PR TITLE
WIP: Update the package

### PR DESCRIPTION
**Pull request by meggart**
This is an attempt at updating the package. In the process I separated the C API a bit more from the Julia code by generating a wrapper using Clang.jl. In addition, this new version is using the artifact system instead of a BinDeps build recipe. Still WIP is updating the documentation to use Documenter instead of Docile and fixing the tests. 

I have also implemented a prototype dictionary-like interface which might help when one wants to use this DB as a simple key-value store. Not sure if this is in the scope of this package, I could also implement the `LMDBDict` type further downstream. 

Any feedback would be most welcome.

### CODE REVIEW

**Comment by meggart** [comment]
The old test suite is running and the documentation build process is updated. All that remains is to document and test new functionality (i.e. iterator over values and pairs of the database and the new dict-like type).

**Comment by meggart** [comment]
Bump. 

@wildart in case you lost interest and do not plan to maintain this package any longer I would volunteer to register it for Julia 1.x and keep up maintenance. Just let me know what you plans are...

**Comment by meggart** [comment]
Another reminder. As I said, I could also maintain this package if you want to. I kind of really need this update, so another option would that I fork the package under a different name, giving credits to you as the original author. However, getting a quick reply would be very helpful.

**Comment by wildart** [comment]
I gave you a rw access to this repo, so you can merge your PR.

**Comment by meggart** [comment]
Thanks a lot!

**Pull request merged**
